exports.Novice = [ { bib_number: 100,
    lastname: 'Feest',
    firstname: 'Alexander',
    division: 'novice',
    role: 'follow' },
  { bib_number: 101,
    lastname: 'Lind',
    firstname: 'Elias',
    division: 'novice',
    role: 'follow' },
  { bib_number: 102,
    lastname: 'Predovic',
    firstname: 'Raven',
    division: 'novice',
    role: 'follow' },
  { bib_number: 103,
    lastname: 'Roberts',
    firstname: 'Luther',
    division: 'novice',
    role: 'follow' },
  { bib_number: 104,
    lastname: 'Monahan',
    firstname: 'Paul',
    division: 'novice',
    role: 'follow' },
  { bib_number: 105,
    lastname: 'Wolff',
    firstname: 'Lucas',
    division: 'novice',
    role: 'follow' },
  { bib_number: 106,
    lastname: 'Dibbert',
    firstname: 'Berneice',
    division: 'novice',
    role: 'follow' },
  { bib_number: 107,
    lastname: 'Hermann',
    firstname: 'Shanel',
    division: 'novice',
    role: 'follow' },
  { bib_number: 108,
    lastname: 'Schimmel',
    firstname: 'Hipolito',
    division: 'novice',
    role: 'follow' },
  { bib_number: 109,
    lastname: 'Crist',
    firstname: 'Gail',
    division: 'novice',
    role: 'follow' },
  { bib_number: 110,
    lastname: 'Heathcote',
    firstname: 'Amara',
    division: 'novice',
    role: 'follow' },
  { bib_number: 111,
    lastname: 'Jacobi',
    firstname: 'Glenda',
    division: 'novice',
    role: 'follow' },
  { bib_number: 112,
    lastname: 'Cummerata',
    firstname: 'Enola',
    division: 'novice',
    role: 'follow' },
  { bib_number: 113,
    lastname: 'Weissnat',
    firstname: 'Korbin',
    division: 'novice',
    role: 'follow' },
  { bib_number: 114,
    lastname: 'Hyatt',
    firstname: 'Jonatan',
    division: 'novice',
    role: 'follow' },
  { bib_number: 115,
    lastname: 'Robel',
    firstname: 'Colleen',
    division: 'novice',
    role: 'follow' },
  { bib_number: 116,
    lastname: 'Marks',
    firstname: 'Cristina',
    division: 'novice',
    role: 'follow' },
  { bib_number: 117,
    lastname: 'Brakus',
    firstname: 'Ewell',
    division: 'novice',
    role: 'follow' },
  { bib_number: 118,
    lastname: 'Stanton',
    firstname: 'Hannah',
    division: 'novice',
    role: 'follow' },
  { bib_number: 119,
    lastname: 'Blick',
    firstname: 'Laurence',
    division: 'novice',
    role: 'follow' },
  { bib_number: 120,
    lastname: 'Kunde',
    firstname: 'Tremayne',
    division: 'novice',
    role: 'follow' },
  { bib_number: 121,
    lastname: 'Kohler',
    firstname: 'Michale',
    division: 'novice',
    role: 'follow' },
  { bib_number: 122,
    lastname: 'Greenfelder',
    firstname: 'Aditya',
    division: 'novice',
    role: 'follow' },
  { bib_number: 123,
    lastname: 'Wilderman',
    firstname: 'Alysson',
    division: 'novice',
    role: 'follow' },
  { bib_number: 124,
    lastname: 'Kassulke',
    firstname: 'Mike',
    division: 'novice',
    role: 'follow' },
  { bib_number: 125,
    lastname: 'Reynolds',
    firstname: 'Tatyana',
    division: 'novice',
    role: 'follow' },
  { bib_number: 126,
    lastname: 'Smitham',
    firstname: 'Kyleigh',
    division: 'novice',
    role: 'follow' },
  { bib_number: 127,
    lastname: 'Donnelly',
    firstname: 'Misael',
    division: 'novice',
    role: 'follow' },
  { bib_number: 128,
    lastname: 'Jenkins',
    firstname: 'Ally',
    division: 'novice',
    role: 'follow' },
  { bib_number: 129,
    lastname: 'Swift',
    firstname: 'Manley',
    division: 'novice',
    role: 'follow' },
  { bib_number: 130,
    lastname: 'Boyle',
    firstname: 'Sterling',
    division: 'novice',
    role: 'follow' },
  { bib_number: 131,
    lastname: 'Dare',
    firstname: 'Sabrina',
    division: 'novice',
    role: 'follow' },
  { bib_number: 132,
    lastname: 'Hudson',
    firstname: 'Darrell',
    division: 'novice',
    role: 'follow' },
  { bib_number: 133,
    lastname: 'Rogahn',
    firstname: 'Stefan',
    division: 'novice',
    role: 'follow' },
  { bib_number: 134,
    lastname: 'Wisozk',
    firstname: 'Thalia',
    division: 'novice',
    role: 'follow' },
  { bib_number: 135,
    lastname: 'Haley',
    firstname: 'Cesar',
    division: 'novice',
    role: 'follow' },
  { bib_number: 136,
    lastname: 'Stracke',
    firstname: 'Germaine',
    division: 'novice',
    role: 'follow' },
  { bib_number: 137,
    lastname: 'McClure',
    firstname: 'Domenick',
    division: 'novice',
    role: 'follow' },
  { bib_number: 138,
    lastname: 'Nicolas',
    firstname: 'Shania',
    division: 'novice',
    role: 'follow' },
  { bib_number: 139,
    lastname: 'Hoeger',
    firstname: 'Myriam',
    division: 'novice',
    role: 'follow' },
  { bib_number: 140,
    lastname: 'Heller',
    firstname: 'Leonel',
    division: 'novice',
    role: 'follow' },
  { bib_number: 141,
    lastname: 'Klein',
    firstname: 'Wilber',
    division: 'novice',
    role: 'follow' },
  { bib_number: 142,
    lastname: 'Stanton',
    firstname: 'Justice',
    division: 'novice',
    role: 'follow' },
  { bib_number: 143,
    lastname: 'Casper',
    firstname: 'Sanford',
    division: 'novice',
    role: 'follow' },
  { bib_number: 144,
    lastname: 'Schiller',
    firstname: 'Kavon',
    division: 'novice',
    role: 'follow' },
  { bib_number: 145,
    lastname: 'Zemlak',
    firstname: 'Kayli',
    division: 'novice',
    role: 'follow' },
  { bib_number: 146,
    lastname: 'Lakin',
    firstname: 'Tavares',
    division: 'novice',
    role: 'follow' },
  { bib_number: 147,
    lastname: 'Emard',
    firstname: 'Jovan',
    division: 'novice',
    role: 'follow' },
  { bib_number: 148,
    lastname: 'Lehner',
    firstname: 'Dorothea',
    division: 'novice',
    role: 'follow' },
  { bib_number: 149,
    lastname: 'Keebler',
    firstname: 'Marlin',
    division: 'novice',
    role: 'follow' },
  { bib_number: 150,
    lastname: 'Koelpin',
    firstname: 'Darian',
    division: 'novice',
    role: 'follow' },
  { bib_number: 151,
    lastname: 'Brakus',
    firstname: 'Kathleen',
    division: 'novice',
    role: 'follow' },
  { bib_number: 152,
    lastname: 'Streich',
    firstname: 'Ernestina',
    division: 'novice',
    role: 'follow' },
  { bib_number: 153,
    lastname: 'Gottlieb',
    firstname: 'Stella',
    division: 'novice',
    role: 'follow' },
  { bib_number: 154,
    lastname: 'Anderson',
    firstname: 'Gregoria',
    division: 'novice',
    role: 'follow' },
  { bib_number: 155,
    lastname: 'Reilly',
    firstname: 'Virginie',
    division: 'novice',
    role: 'follow' },
  { bib_number: 156,
    lastname: 'Grady',
    firstname: 'Aubrey',
    division: 'novice',
    role: 'follow' },
  { bib_number: 157,
    lastname: 'Klein',
    firstname: 'Adaline',
    division: 'novice',
    role: 'follow' },
  { bib_number: 158,
    lastname: 'OHara',
    firstname: 'Tomasa',
    division: 'novice',
    role: 'follow' },
  { bib_number: 159,
    lastname: 'Beatty',
    firstname: 'Barry',
    division: 'novice',
    role: 'follow' },
  { bib_number: 160,
    lastname: 'Kshlerin',
    firstname: 'Aurelio',
    division: 'novice',
    role: 'follow' },
  { bib_number: 161,
    lastname: 'Cole',
    firstname: 'Margaret',
    division: 'novice',
    role: 'follow' },
  { bib_number: 162,
    lastname: 'Connelly',
    firstname: 'Eriberto',
    division: 'novice',
    role: 'follow' },
  { bib_number: 163,
    lastname: 'Trantow',
    firstname: 'Breanne',
    division: 'novice',
    role: 'follow' },
  { bib_number: 164,
    lastname: 'Bailey',
    firstname: 'Jerad',
    division: 'novice',
    role: 'follow' },
  { bib_number: 165,
    lastname: 'Ankunding',
    firstname: 'Seamus',
    division: 'novice',
    role: 'follow' },
  { bib_number: 166,
    lastname: 'Bayer',
    firstname: 'Craig',
    division: 'novice',
    role: 'follow' },
  { bib_number: 167,
    lastname: 'Macejkovic',
    firstname: 'Alice',
    division: 'novice',
    role: 'follow' },
  { bib_number: 168,
    lastname: 'Robel',
    firstname: 'Jalyn',
    division: 'novice',
    role: 'follow' },
  { bib_number: 169,
    lastname: 'OConnell',
    firstname: 'Cloyd',
    division: 'novice',
    role: 'follow' },
  { bib_number: 170,
    lastname: 'Morar',
    firstname: 'Lloyd',
    division: 'novice',
    role: 'follow' },
  { bib_number: 171,
    lastname: 'Lowe',
    firstname: 'Mireille',
    division: 'novice',
    role: 'follow' },
  { bib_number: 172,
    lastname: 'Barton',
    firstname: 'Katelin',
    division: 'novice',
    role: 'follow' },
  { bib_number: 173,
    lastname: 'Prosacco',
    firstname: 'Dameon',
    division: 'novice',
    role: 'follow' },
  { bib_number: 174,
    lastname: 'Yost',
    firstname: 'Assunta',
    division: 'novice',
    role: 'follow' },
  { bib_number: 175,
    lastname: 'Lynch',
    firstname: 'Isadore',
    division: 'novice',
    role: 'follow' },
  { bib_number: 176,
    lastname: 'Rath',
    firstname: 'Margaretta',
    division: 'novice',
    role: 'follow' },
  { bib_number: 177,
    lastname: 'Harris',
    firstname: 'Lou',
    division: 'novice',
    role: 'follow' },
  { bib_number: 178,
    lastname: 'Kozey',
    firstname: 'Gia',
    division: 'novice',
    role: 'follow' },
  { bib_number: 179,
    lastname: 'Kohler',
    firstname: 'Oceane',
    division: 'novice',
    role: 'follow' },
  { bib_number: 200,
    lastname: 'Koss',
    firstname: 'Beryl',
    division: 'novice',
    role: 'lead' },
  { bib_number: 201,
    lastname: 'Dicki',
    firstname: 'Amara',
    division: 'novice',
    role: 'lead' },
  { bib_number: 202,
    lastname: 'Olson',
    firstname: 'Darrick',
    division: 'novice',
    role: 'lead' },
  { bib_number: 203,
    lastname: 'Mante',
    firstname: 'Marvin',
    division: 'novice',
    role: 'lead' },
  { bib_number: 204,
    lastname: 'Mitchell',
    firstname: 'Olaf',
    division: 'novice',
    role: 'lead' },
  { bib_number: 205,
    lastname: 'Lebsack',
    firstname: 'Ashlynn',
    division: 'novice',
    role: 'lead' },
  { bib_number: 206,
    lastname: 'Hauck',
    firstname: 'Tyler',
    division: 'novice',
    role: 'lead' },
  { bib_number: 207,
    lastname: 'Gislason',
    firstname: 'Sydnie',
    division: 'novice',
    role: 'lead' },
  { bib_number: 208,
    lastname: 'Dietrich',
    firstname: 'Nestor',
    division: 'novice',
    role: 'lead' },
  { bib_number: 209,
    lastname: 'Boehm',
    firstname: 'Mitchel',
    division: 'novice',
    role: 'lead' },
  { bib_number: 210,
    lastname: 'Olson',
    firstname: 'Cassandra',
    division: 'novice',
    role: 'lead' },
  { bib_number: 211,
    lastname: 'Wisoky',
    firstname: 'Lura',
    division: 'novice',
    role: 'lead' },
  { bib_number: 212,
    lastname: 'Ebert',
    firstname: 'Giuseppe',
    division: 'novice',
    role: 'lead' },
  { bib_number: 213,
    lastname: 'Wilkinson',
    firstname: 'Jasper',
    division: 'novice',
    role: 'lead' },
  { bib_number: 214,
    lastname: 'Powlowski',
    firstname: 'Sage',
    division: 'novice',
    role: 'lead' },
  { bib_number: 215,
    lastname: 'Kovacek',
    firstname: 'Aylin',
    division: 'novice',
    role: 'lead' },
  { bib_number: 216,
    lastname: 'Bartell',
    firstname: 'Ramon',
    division: 'novice',
    role: 'lead' },
  { bib_number: 217,
    lastname: 'Jaskolski',
    firstname: 'Luigi',
    division: 'novice',
    role: 'lead' },
  { bib_number: 218,
    lastname: 'Boehm',
    firstname: 'Gregorio',
    division: 'novice',
    role: 'lead' },
  { bib_number: 219,
    lastname: 'Hickle',
    firstname: 'Phyllis',
    division: 'novice',
    role: 'lead' },
  { bib_number: 220,
    lastname: 'Vandervort',
    firstname: 'Lamar',
    division: 'novice',
    role: 'lead' },
  { bib_number: 221,
    lastname: 'Roob',
    firstname: 'Duncan',
    division: 'novice',
    role: 'lead' },
  { bib_number: 222,
    lastname: 'Abshire',
    firstname: 'Shemar',
    division: 'novice',
    role: 'lead' },
  { bib_number: 223,
    lastname: 'Dibbert',
    firstname: 'Lazaro',
    division: 'novice',
    role: 'lead' },
  { bib_number: 224,
    lastname: 'Cronin',
    firstname: 'Trey',
    division: 'novice',
    role: 'lead' },
  { bib_number: 225,
    lastname: 'West',
    firstname: 'Allene',
    division: 'novice',
    role: 'lead' },
  { bib_number: 226,
    lastname: 'Welch',
    firstname: 'Ivy',
    division: 'novice',
    role: 'lead' },
  { bib_number: 227,
    lastname: 'Kuphal',
    firstname: 'Kiel',
    division: 'novice',
    role: 'lead' },
  { bib_number: 228,
    lastname: 'Considine',
    firstname: 'Nat',
    division: 'novice',
    role: 'lead' },
  { bib_number: 229,
    lastname: 'Kautzer',
    firstname: 'Cameron',
    division: 'novice',
    role: 'lead' } ];